export const MinecraftConstants = {
  // Block Types
  STONE: 1,
  GRASS: 2,
  DIRT: 3,
  COAL_ORE: 4,
  IRON_ORE: 5,
  GOLD_ORE: 6,
  DIAMOND_ORE: 7,
  EMERALD_ORE: 8,
  REDSTONE_ORE: 9,
  LAPIS_LAZULI_ORE: 10,
  SAND: 11,
  GRAVEL: 12,
  COBBLESTONE: 13,
  WOOD: 14,

  // Tools
  WOODEN_PICKAXE: 100,
  STONE_PICKAXE: 101,
  IRON_PICKAXE: 102,
  DIAMOND_PICKAXE: 103,
  GOLDEN_PICKAXE: 104,

  // Tool Durability
  WOODEN_PICKAXE_DURABILITY: 10,
  STONE_PICKAXE_DURABILITY: 131,
  IRON_PICKAXE_DURABILITY: 250,
  DIAMOND_PICKAXE_DURABILITY: 1561,
  GOLDEN_PICKAXE_DURABILITY: 32,
  SHEARS_DURABILITY: 238,

  // Tool Levels
  TOOL_LEVEL_WOODEN: 1,
  TOOL_LEVEL_STONE: 2,
  TOOL_LEVEL_IRON: 3,
  TOOL_LEVEL_DIAMOND: 4,
  TOOL_LEVEL_GOLDEN: 5,
} as const; 